### ISSUE TITLE
Is this module still supported?

### ISSUE THREAD

**Issue by zekefast** [artberri/puppet-yarn#5]
This module did not have new  releases for more then a year.

Despite there are number of issues with it.
- Supported only old versions of `puppetlabs-apt` module (current version of `artberri-yarn` (`1.0.0`) is limited by [`< 3.0.0` of `puppetlabs-apt`](https://github.com/artberri/puppet-yarn/blob/master/metadata.json#L86)).
- Flakyness of GPG key for Debian (for [RedHat url source is used]()). Yarn is for debian is laying at https://dl.yarnpkg.com/debian/pubkey.gpg. So `apt::key`'s `source` attribute can be used to install it.
- `apt::source` imply minimal version of `puppetlabs-apt` is `2.0.0` because it rely on [changes made in it](https://forge.puppet.com/puppetlabs/apt/changelog#2015-04-07---supported-release-200) (`key { id =>"...", server => "..." }`). In versions `< 2.0.0` it was `key` instead of `id` and `key_server` instead of `server`.

**Comment by zekefast** [comment]
There is even a pull request already to bix 2nd issue with flakyness of GPG key: https://github.com/artberri/puppet-yarn/pull/1/files

**Comment by simmerz** [comment]
For anyone coming across this, I've forked and published my own version here: https://github.com/initforthe/puppet-yarn (Forge module is here: https://forge.puppet.com/initforthe/yarn)

**Comment by artberri** [comment]
This plugin is not maintained anymore, sorry for the inconvenience:
https://github.com/artberri/puppet-yarn#deprecated-puppet-yarn

Thank you @simmerz for keeping it alive during this time.
