### ISSUE TITLE
Puppet 8x compatibility ?

### ISSUE THREAD

**Issue by flepoutre** [artberri/puppet-yarn#7]
Hello,
Is it possible to create a tag with Puppet 8x compatibility ?
Thanks.

**Comment by flepoutre** [comment]
Hello,
Any news on this subject ?
Thanks.

**Comment by artberri** [comment]
This plugin is not maintained anymore, sorry for the inconvenience:
https://github.com/artberri/puppet-yarn#deprecated-puppet-yarn
